name: httomo-backends
channels:
  - conda-forge
  - httomo
dependencies:
  - conda-forge::pyyaml
  - conda-forge::tomopy=1.15
  - httomo::httomolib=2.1
  - httomo::httomolibgpu=2.1
  - httomo::tomobar
