name: httomo-backends
channels:
  - conda-forge
  - httomo
dependencies:
  - conda-forge::astra-toolbox
  - conda-forge::cupy=12.3.0
  - conda-forge::h5py
  - conda-forge::imageio
  - conda-forge::numpy<2
  - conda-forge::nvtx
  - conda-forge::pyyaml
  - conda-forge::scikit-image
  - conda-forge::toml
  - conda-forge::tomopy=1.15
