name: httomo-backends
channels:
  - conda-forge
  - httomo
dependencies:
  - conda-forge::pyyaml
  - conda-forge::tomopy=1.15
  - conda-forge::mpi4py
  - httomo::httomolib=2.1.2
  - httomo::httomolibgpu=2.1.2
  - httomo::tomobar
