name: httomo-backends
channels:
  - conda-forge
  - httomo
dependencies:
  - conda-forge::cuda-version
  - conda-forge::cupy=12.3.0
  - conda-forge::numpy<2
  - conda-forge::pyyaml
  - conda-forge::tomopy=1.15
