name: Upload Package to PyPI when "v" tag is pushed

# Run the workflow whenever a tag beginning with `v` is pushed to any branch
on:
  push:
    tags:
      - v*

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/httomo-backends
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |        
          $CONDA/bin/conda install conda-forge::tomopy==1.15
          $CONDA/bin/conda install conda-forge::pyyaml
          $CONDA/bin/pip install setuptools wheel
          $CONDA/bin/pip install build          
          $CONDA/bin/pip install httomolib
          $CONDA/bin/pip install --no-deps httomolibgpu
          $CONDA/bin/conda list
      - name: Generate yaml templates
        run: |
          $CONDA/bin/python ./httomo_backends/scripts/yaml_templates_generator.py -i ./httomo_backends/methods_database/packages/backends/tomopy/tomopy_modules.yaml -o ./httomo_backends/yaml_templates/tomopy
          $CONDA/bin/python ./httomo_backends/scripts/yaml_unsupported_tomopy_remove.py -t ./httomo_backends/yaml_templates/tomopy -l ./httomo_backends/methods_database/packages/backends/tomopy/tomopy.yaml
          $CONDA/bin/python ./httomo_backends/scripts/yaml_templates_generator.py -i ./httomo_backends/methods_database/packages/backends/httomolib/httomolib_modules.yaml -o ./httomo_backends/yaml_templates/httomolib
          $CONDA/bin/python ./httomo_backends/scripts/yaml_templates_generator.py -i ./httomo_backends/methods_database/packages/backends/httomolibgpu/httomolibgpu_modules.yaml -o ./httomo_backends/yaml_templates/httomolibgpu
      - name: Build package
        run: |
          $CONDA/bin/python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
