name: Test Httomo Backends

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  iris-gpu:
    runs-on: iris-gpu
    container:
      image: nvidia/cuda:11.6.2-devel-ubi8
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environment.yml
          environment-name: httomo_backends
          post-cleanup: 'all'
          init-shell: bash
          
      - name: Install httomo-backends
        run: |
          micromamba activate httomo_backends
          pip install httomolibgpu
          pip install .[dev]
          micromamba list
                
      - name: Run tests
        run: |
          pytest tests/
